name: moviesanalyzer
services:
  client:
    container_name: client
    build: client
    env_file: client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway

  # ====================== Rabbit - Gateway ======================

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  gateway:
    container_name: gateway
    build: gateway
    ports:
      - 9090:9090
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - envs/gateway/.env.gateway

  # ====================== Sanitizers ======================

  sanitize-movies-0:
    container_name: sanitize-movies-0
    build:
      context: workers
      dockerfile: dockerfiles/sanitize.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/sanitize/.env.movies
    environment:
      - ID=0
      - OUTPUT_COPIES=1,2,1

  # ====================== Filters ======================

  filter-release_date_since_2000-0:
    container_name: filter-release_date_since_2000-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/filter/.env.release_date_since_2000
    environment:
      - ID=0
      - OUTPUT_COPIES=1,1,1

  filter-production_countries_argentina_spain-0:
    container_name: filter-production_countries_argentina_spain-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/filter/.env.production_countries_argentina_spain
    environment:
      - ID=0
      - OUTPUT_COPIES=1

  filter-release_date_upto_2010-0:
    container_name: filter-release_date_upto_2010-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/filter/.env.release_date_upto_2010
    environment:
      - ID=0
      - OUTPUT_COPIES=1

  filter-release_date_upto_2010-1:
    container_name: filter-release_date_upto_2010-1
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/filter/.env.release_date_upto_2010
    environment:
      - ID=1
      - OUTPUT_COPIES=1

  filter-release_date_upto_2010-2:
    container_name: filter-release_date_upto_2010-2
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/filter/.env.release_date_upto_2010
    environment:
      - ID=2
      - OUTPUT_COPIES=1

  # ====================== Sinks ======================

  sink-1-0:
    container_name: sink-1-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - envs/sink/.env.1
    environment:
      - ID=0
      - OUTPUT_COPIES=1
