name: moviesanalyzer
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  gateway:
    container_name: gateway
    build: gateway
    image: gateway:latest
    env_file: gateway/.env
    ports:
      - 9090:9090
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    build: client
    image: client:latest
    env_file: client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway

  sanitize-movies:
    container_name: sanitize
    build: workers/sanitize
    image: sanitize:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      # Rabbit configuration
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - INPUT_EXCHANGE_NAME=gateway
      - INPUT_EXCHANGE_TYPE=direct
      - INPUT_QUEUES=movies
      - INPUT_QUEUE_KEYS=movies
      - OUTPUT_EXCHANGE_NAME=sanitize_movies
      - OUTPUT_EXCHANGE_TYPE=fanout
      - OUTPUT_QUEUES=filter_release_date_[2000; ...)
      - OUTPUT_QUEUE_KEYS=

      # Worker
      - SELECT=id,title,genres,release_date,overview,production_countries,spoken_languages,budget,revenue

      # Sanitize
      - HANDLER=movies

