name: moviesanalyzer
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    logging:
      driver: none

  gateway:
    container_name: gateway
    build: gateway
    image: gateway:latest
    env_file: gateway/.env
    environment:
      - OUTPUT_EXCHANGE_NAME=gateway
      - OUTPUT_EXCHANGE_TYPE=direct
      - OUTPUT_QUEUE_NAMES=movies,credits,ratings
      - OUTPUT_QUEUE_KEYS=movies,credits,ratings
    ports:
      - 9090:9090
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    build: client
    image: client:latest
    env_file: client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway

  sanitize-movies:
    container_name: sanitize-movies
    image: sanitize:latest
    build:
      context: workers
      dockerfile: dockerfiles/sanitize.Dockerfile
    env_file: workers/.env
    environment:
      # Input
      - INPUT_EXCHANGE_NAME=gateway
      - INPUT_EXCHANGE_TYPE=direct
      - INPUT_QUEUE_NAMES=movies
      - INPUT_QUEUE_KEYS=movies

      # Output
      - OUTPUT_EXCHANGE_NAME=sanitize_movies
      - OUTPUT_EXCHANGE_TYPE=fanout
      - OUTPUT_QUEUE_NAMES=filter_release_date_since_2000
      - OUTPUT_QUEUE_KEYS=

      # Worker
      - SELECT=id,title,genres,release_date,overview,production_countries,spoken_languages,budget,revenue

      # Sanitize
      - HANDLER=movies
    depends_on:
      rabbitmq:
        condition: service_healthy

