services:
  client:
    container_name: client
    build: client
    env_file: client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  gateway:
    container_name: gateway
    build: gateway
    ports:
      - 9090:9090
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - configs/gateway/.env.gateway

  #### Sanitizers ####
  sanitize-movies-0:
    container_name: sanitize-movies-0
    build:
      context: workers
      dockerfile: dockerfiles/sanitize.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sanitize/.env.movies
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1,1,1

  sanitize-credits-0:
    container_name: sanitize-credits-0
    build:
      context: workers
      dockerfile: dockerfiles/sanitize.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sanitize/.env.credits
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  sanitize-ratings-0:
    container_name: sanitize-ratings-0
    build:
      context: workers
      dockerfile: dockerfiles/sanitize.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sanitize/.env.ratings
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=2

  #### Filters ####
  filter-production_countries_length-0:
    container_name: filter-production_countries_length-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.production_countries_length
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  filter-release_date_since_2000-0:
    container_name: filter-release_date_since_2000-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.release_date_since_2000
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=2,1

  filter-release_date_upto_2010-0:
    container_name: filter-release_date_upto_2010-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.release_date_upto_2010
    environment:
      - ID=0
      - INPUT_COPIES=2
      - OUTPUT_COPIES=1

  filter-production_countries_argentina-0:
    container_name: filter-production_countries_argentina-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.production_countries_argentina
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1,2

  filter-production_countries_argentina_spain-0:
    container_name: filter-production_countries_argentina_spain-0
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.production_countries_argentina_spain
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  filter-production_countries_argentina_spain-1:
    container_name: filter-production_countries_argentina_spain-1
    build:
      context: workers
      dockerfile: dockerfiles/filter.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/filter/.env.production_countries_argentina_spain
    environment:
      - ID=1
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  #### Exploders ####
  explode-cast-0:
    container_name: explode-cast-0
    build:
      context: workers
      dockerfile: dockerfiles/explode.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/explode/.env.cast
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  #### Exploders ####
  explode-cast-1:
    container_name: explode-cast-1
    build:
      context: workers
      dockerfile: dockerfiles/explode.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/explode/.env.cast
    environment:
      - ID=1
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  explode-production_countries-0:
    container_name: explode-production_countries-0
    build:
      context: workers
      dockerfile: dockerfiles/explode.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/explode/.env.production_countries
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=2

  #### Group by ####
  groupby-id_title_mean_rating-0:
    container_name: groupby-id_title_mean_rating-0
    build:
      context: workers
      dockerfile: dockerfiles/groupby.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/groupby/.env.id_title_mean_rating
    environment:
      - ID=0
      - INPUT_COPIES=2
      - OUTPUT_COPIES=1

  groupby-sentiment_mean_rate_revenue_budget-0:
    container_name: groupby-sentiment_mean_rate_revenue_budget-0
    build:
      context: workers
      dockerfile: dockerfiles/groupby.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/groupby/.env.sentiment_mean_rate_revenue_budget
    environment:
      - ID=0
      - INPUT_COPIES=2
      - OUTPUT_COPIES=1

  groupby-country_sum_budget-0:
    container_name: groupby-country_sum_budget-0
    build:
      context: workers
      dockerfile: dockerfiles/groupby.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/groupby/.env.country_sum_budget
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  groupby-country_sum_budget-1:
    container_name: groupby-country_sum_budget-1
    build:
      context: workers
      dockerfile: dockerfiles/groupby.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/groupby/.env.country_sum_budget
    environment:
      - ID=1
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  groupby-actor_count-0:
    container_name: groupby-actor_count-0
    build:
      context: workers
      dockerfile: dockerfiles/groupby.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/groupby/.env.actor_count
    environment:
      - ID=0
      - INPUT_COPIES=2
      - OUTPUT_COPIES=1

  #### Divider ####
  divider-0:
    container_name: divider-0
    build:
      context: workers
      dockerfile: dockerfiles/divider.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/divider/.env.revenue_budget
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=2

  #### Sentiment ####
  sentiment-0:
    container_name: sentiment-0
    build:
      context: workers
      dockerfile: dockerfiles/sentiment.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sentiment/.env.overview
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  #### Sentiment ####
  sentiment-1:
    container_name: sentiment-1
    build:
      context: workers
      dockerfile: dockerfiles/sentiment.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sentiment/.env.overview
    environment:
      - ID=1
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  #### Tops #### 
  top-10_count-0:
    container_name: top-10_count-0
    build:
      context: workers
      dockerfile: dockerfiles/top.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/top/.env.10_count
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  top-5_budget-0:
    container_name: top-5_budget-0
    build:
      context: workers
      dockerfile: dockerfiles/top.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/top/.env.5_budget
    environment:
      - ID=0
      - INPUT_COPIES=2
      - OUTPUT_COPIES=1

  #### Minmax ####
  minmax-rating-0:
    container_name: minmax-rating-0
    build:
      context: workers
      dockerfile: dockerfiles/minmax.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/minmax/.env.rating
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  #### Joins ####
  join-id_movieid-0:
    container_name: join-id_movieid-0
    build:
      context: workers
      dockerfile: dockerfiles/join.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/join/.env.id_movieId
    environment:
      - ID=0
      - INPUT_COPIES=1,1
      - OUTPUT_COPIES=1

  #### Joins ####
  join-id_movieid-1:
    container_name: join-id_movieid-1
    build:
      context: workers
      dockerfile: dockerfiles/join.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/join/.env.id_movieId
    environment:
      - ID=1
      - INPUT_COPIES=1,1
      - OUTPUT_COPIES=1

  join-id_id-0:
    container_name: join-id_id-0
    build:
      context: workers
      dockerfile: dockerfiles/join.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/join/.env.id_id
    environment:
      - ID=0
      - INPUT_COPIES=1,1
      - OUTPUT_COPIES=2

  #### Sinks ####
  sink-1-0:
    container_name: sink-1-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sink/.env.1
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  sink-2-0:
    container_name: sink-2-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sink/.env.2
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  sink-3-0:
    container_name: sink-3-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sink/.env.3
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  sink-4-0:
    container_name: sink-4-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sink/.env.4
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1

  sink-5-0:
    container_name: sink-5-0
    build:
      context: workers
      dockerfile: dockerfiles/sink.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - workers/.env
      - configs/sink/.env.5
    environment:
      - ID=0
      - INPUT_COPIES=1
      - OUTPUT_COPIES=1
