name: moviesanalyzer
services:
  gateway:
    container_name: gateway
    build: gateway
    image: gateway:latest
    env_file: gateway/.env
    ports:
      - 9090:9090

  client:
    container_name: client
    build: client
    image: client:latest
    env_file: client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway

  filter::
    container_name: filter
    build: workers/filter
    image: filter:latest
    env_file: workers/.env
    environment:
      - INPUT_QUEUES=
      - OUTPUT_QUEUES=
      - FILTER_RANGE=
      - FILTER_CONTAINS=
      - FILTER_LEN=
      - FILTER_KEY=cast
