name: moviesanalyzer
services:
  gateway:
    container_name: gateway
    build: src/gateway
    image: gateway:latest
    env_file: src/gateway/.env
    ports:
      - 9090:9090

  client:
    container_name: client
    build: src/client
    image: client:latest
    env_file: src/client/.env
    volumes:
      - .data:/data
    depends_on:
      - gateway